name: Waka Readme Weekly

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */13 * * *'

jobs:
  update-readme:
    name: WakaReadme DevMetrics Weekly
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SECTION_NAME: waka-weekly
          SHOW_COMMIT: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_TOTAL_CODE_TIME: "False"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_PROJECTS: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_LOC_CHART: "False"
          SHOW_UPDATED_DATE: "False"
          SHOW_TIMEZONE: "False"
          SHOW_EDITORS: "False"
